'use client';
import Head from "next/head";
import Image from "next/image";
import Button from '@mui/material/Button';
import React from 'react';

export default function Home() {

  const handleSubscription = async (e) => {
    try {
      const res = await fetch('/api/route', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ priceId: "price_1OHWdTKwZOLBQ6VV36IQAx6L" })
      });

      if (!res.ok) {
        throw new Error(`Error: ${res.status}`);
      }

      const data = await res.json();

      if (data.url) {
        // 使用 JavaScript 的 window.location.assign 进行跳转
        window.location.assign(data.url);
      } else {
        console.error('No URL returned from the API');
      }
    } catch (error) {
      console.error('Failed to call API:', error);
    }
  };


  return (
    <div>
      <Head>
        <title>Physical NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Buy my physical NFTs</h1>
        <div style={{ display: 'flex', gap: '50px'}}>
          <div>
            <Image
              src="/1.jpg"
              alt="NFT"
              width={150}
              height={150}
            />
            <h3>Very expensive art piece 1</h3>
            <Button id="al" aria-label="Name" variant="contained" color="primary" onClick={handleSubscription}>BUY!</Button>
          </div>
          <div>
            <Image
              src="/2.jpg"
              alt="NFT"
              width={150}
              height={150}
            />
            <h3>Very expensive art piece 2</h3>
          </div>
        </div>
      </main>
      </div>
  )
}
